#!/usr/bin/env node
// ════════════════════════════════════════════════════════════════════════
// jobs/scan_watchdog_vrt2.js · CLAW VRT2 · v3.1.1
//
// Fail-loud monitoring. Runs every 30 minutes via launchd. Checks:
//   0. CRDO server liveness (prerequisite for accurate daemon check)
//   1. browser_runner daemon heartbeat (only alerts if server is up)
//   2. Stuck RUNNING tasks (>5 min) — auto-heals to FAILED
//   3. Failure burst rate (>5 failures/hour = possible rate limit)
//   4. claude.ai login expired (detected via LOGIN_EXPIRED result status)
//   5. Daily brief generated by 6:30am ET
//   6. Browser queue depth (backlog warning)
//   7. Unprocessed result backlog (consumer falling behind)
//
// Fires macOS notifications via osascript and logs to logs/ALERTS.log.
//
// v3.1.1 fixes:
//   - Distinguishes "daemon dead" from "server down" via /status probe
//     (previously a server restart would fire false CRITICAL alerts)
//   - Stuck-task auto-heal is no longer a noisy alert; only escalates if
//     3+ tasks stuck simultaneously (indicates persistent daemon problem)
//   - Daily brief check window tightened from 7am to 6:30am ET so failures
//     are noticed before market open
//   - Adds unprocessed result backlog check (consumer falling behind)
//   - Full async IIFE structure — no busy-waits, no execSync for sleep
//
// Usage: node jobs/scan_watchdog_vrt2.js
// ════════════════════════════════════════════════════════════════════════

const path = require('path');
const fs = require('fs');
const http = require('http');
const { execSync } = require('child_process');
const Database = require('better-sqlite3');
const { PORT: SERVER_PORT } = require('../lib/config');

const ROOT = path.resolve(__dirname, '..');
const DB_PATH = path.join(ROOT, 'vrt2.db');
const ALERTS_LOG = path.join(ROOT, 'logs', 'ALERTS.log');

if (!fs.existsSync(path.dirname(ALERTS_LOG))) {
  fs.mkdirSync(path.dirname(ALERTS_LOG), { recursive: true });
}

// ── HELPERS ─────────────────────────────────────────────────────────────
const NOW = Date.now();
const ALERTS = [];

function alert(severity, code, msg) {
  ALERTS.push({ severity: severity, code: code, msg: msg });
}

function notify(title, message) {
  // macOS notification via osascript. Silently no-ops on non-macOS.
  try {
    const escapedTitle = title.replace(/"/g, '\\"');
    const escapedMsg = message.replace(/"/g, '\\"').replace(/\n/g, ' ').slice(0, 300);
    execSync(
      'osascript -e \'display notification "' + escapedMsg + '" with title "' + escapedTitle + '" sound name "Basso"\'',
      { stdio: 'ignore', timeout: 3000 }
    );
  } catch (e) {
    // Not on macOS or osascript unavailable — log only
  }
}

// Promise-based HTTP GET with hard timeout. No third-party deps.
function pingServer() {
  return new Promise(function(resolve) {
    const req = http.request({
      hostname: '127.0.0.1',
      port: SERVER_PORT,
      path: '/status',
      method: 'GET'
    }, function(res) {
      // Drain body so the socket closes cleanly
      res.on('data', function() {});
      res.on('end', function() { resolve(res.statusCode === 200); });
      res.on('error', function() { resolve(false); });
    });
    req.on('error', function() { resolve(false); });
    req.setTimeout(3000, function() {
      req.destroy();
      resolve(false);
    });
    req.end();
  });
}

// Compute current ET hour/minute for schedule-aware checks
function getETTime() {
  const d = new Date(NOW);
  const etHourStr = d.toLocaleString('en-US', {
    timeZone: 'America/New_York',
    hour: '2-digit',
    hour12: false
  });
  const etMinStr = d.toLocaleString('en-US', {
    timeZone: 'America/New_York',
    minute: '2-digit'
  });
  const etDateStr = d.toLocaleDateString('en-CA', { timeZone: 'America/New_York' });
  return {
    hour: parseInt(etHourStr, 10),
    minute: parseInt(etMinStr, 10),
    date: etDateStr
  };
}

// ── MAIN (async IIFE) ───────────────────────────────────────────────────
(async function main() {
  console.log('CLAW VRT2 — scan_watchdog v3.1.1');
  console.log('Time:', new Date(NOW).toISOString());

  // Open DB — read-write because we auto-heal stuck tasks
  let db;
  try {
    db = new Database(DB_PATH, { readonly: false });
    db.pragma('journal_mode = WAL');
  } catch (e) {
    console.error('FATAL: could not open database at ' + DB_PATH + ': ' + e.message);
    process.exit(2);
  }

  const et = getETTime();
  console.log('ET time:', et.hour + ':' + String(et.minute).padStart(2, '0'), 'on', et.date);
  console.log('');

  // ── CHECK 0: server liveness ─────────────────────────────────────────
  // Prerequisite for accurate heartbeat interpretation. If the server is
  // down, the daemon can't POST heartbeats even when fully healthy — a
  // stale heartbeat tells us nothing about daemon health in that state.
  const serverUp = await pingServer();
  if (serverUp) {
    console.log('  ✓ server reachable at 127.0.0.1:' + SERVER_PORT);
  } else {
    console.log('  ⚠ server NOT reachable at 127.0.0.1:' + SERVER_PORT);
    alert('WARNING', 'SERVER_DOWN',
      'CRDO server not responding on port ' + SERVER_PORT +
      '. Daemon heartbeat checks skipped (would produce false alarms).');
  }

  // ── CHECK 1: browser_runner daemon heartbeat ─────────────────────────
  // Only meaningful when server is up. When server is down, the daemon
  // literally cannot write heartbeats even when healthy.
  let lastBeat = null;
  try {
    lastBeat = db.prepare(
      "SELECT * FROM scan_heartbeats WHERE daemon_name = 'browser_runner_vrt2' " +
      "ORDER BY ts DESC LIMIT 1"
    ).get();
  } catch (e) {
    alert('ERROR', 'NO_HEARTBEAT_TABLE',
      'scan_heartbeats table missing — run migrate_v3_1.js');
  }

  if (!lastBeat) {
    if (serverUp) {
      alert('CRITICAL', 'NO_HEARTBEAT',
        'browser_runner_vrt2 has never sent a heartbeat. Daemon never started?');
    } else {
      console.log('  · no heartbeat recorded (server down — cannot distinguish from daemon dead)');
    }
  } else {
    const beatAge = NOW - lastBeat.ts;
    const beatAgeMin = Math.round(beatAge / 60000);
    if (!serverUp) {
      console.log('  · daemon heartbeat ' + beatAgeMin + ' min ago (server down — skipping alert)');
    } else if (beatAge > 15 * 60 * 1000) {
      alert('CRITICAL', 'STALE_HEARTBEAT',
        'browser_runner_vrt2 last heartbeat ' + beatAgeMin + ' min ago. Daemon may be dead.');
    } else if (beatAge > 5 * 60 * 1000) {
      alert('WARNING', 'OLD_HEARTBEAT',
        'browser_runner_vrt2 heartbeat ' + beatAgeMin + ' min old (expected <2 min)');
    } else {
      console.log('  ✓ daemon heartbeat OK (' + beatAgeMin + ' min ago)');
    }
  }

  // ── CHECK 2: stuck RUNNING tasks (self-heal) ─────────────────────────
  // Not a noisy alert unless 3+ tasks are stuck simultaneously. A single
  // stuck task is usually just a slow scrape that can be retried.
  try {
    const stuck = db.prepare(
      "SELECT task_id, task_type, hypothesis_id, started_ts " +
      "FROM browser_tasks " +
      "WHERE status = 'RUNNING' AND started_ts < ?"
    ).all(NOW - 5 * 60 * 1000);

    if (stuck.length > 0) {
      const markFailed = db.prepare(
        "UPDATE browser_tasks SET status = 'FAILED', completed_ts = ?, " +
        "notes = COALESCE(notes,'') || ' [watchdog: timeout]' WHERE task_id = ?"
      );
      const healMany = db.transaction(function(tasks) {
        for (const t of tasks) markFailed.run(NOW, t.task_id);
      });
      healMany(stuck);

      console.log('  ⚠ auto-healed ' + stuck.length + ' stuck task(s): ' +
        stuck.map(function(t) { return t.task_id + '/' + t.task_type; }).join(', '));

      if (stuck.length >= 3) {
        alert('WARNING', 'STUCK_TASKS_HIGH',
          stuck.length + ' tasks stuck simultaneously — daemon may be degraded');
      }
    } else {
      console.log('  ✓ no stuck tasks');
    }
  } catch (e) {
    alert('ERROR', 'STUCK_CHECK_FAIL', e.message);
  }

  // ── CHECK 3: failure burst (possible rate limit / login expired) ────
  try {
    const recentFails = db.prepare(
      "SELECT COUNT(*) AS n FROM browser_tasks " +
      "WHERE status = 'FAILED' AND completed_ts > ?"
    ).get(NOW - 60 * 60 * 1000).n;

    if (recentFails > 5) {
      alert('CRITICAL', 'FAILURE_BURST',
        recentFails + ' task failures in last hour. Possible rate limit or claude.ai login expired.');
    } else if (recentFails > 0) {
      console.log('  ⚠ ' + recentFails + ' failure(s) in last hour (under threshold)');
    } else {
      console.log('  ✓ no recent failures');
    }
  } catch (e) {
    alert('ERROR', 'FAIL_CHECK_FAIL', e.message);
  }

  // ── CHECK 4: claude.ai login expired ─────────────────────────────────
  // The runner sets result.status='LOGIN_EXPIRED' when it detects the
  // claude.ai session has expired in the persistent profile. Any such
  // result in the last 6 hours is a CRITICAL — manual re-login needed.
  try {
    const loginExpired = db.prepare(
      "SELECT COUNT(*) AS n FROM browser_task_results " +
      "WHERE status = 'LOGIN_EXPIRED' AND completed_ts > ?"
    ).get(NOW - 6 * 60 * 60 * 1000).n;

    if (loginExpired > 0) {
      alert('CRITICAL', 'LOGIN_EXPIRED',
        'claude.ai login expired in persistent profile. Run: node jobs/browser_runner_vrt2.js --login');
    } else {
      console.log('  ✓ claude.ai login appears valid');
    }
  } catch (e) {
    // browser_task_results might not exist on fresh install
  }

  // ── CHECK 5: daily brief generation ──────────────────────────────────
  // Check after 6:30am ET (daily review fires at 6:00, expect brief by 6:30
  // assuming ~20-25 min of semantic review work). Tightened from 7am so
  // failures are caught before market open at 9:30am ET.
  try {
    const etHour = et.hour;
    const etMin = et.minute;
    const afterReviewWindow = (etHour > 6) || (etHour === 6 && etMin >= 30);
    const beforeMidnight = etHour < 23;

    if (afterReviewWindow && beforeMidnight) {
      const briefToday = db.prepare(
        "SELECT brief_date, generated_ts FROM daily_briefs WHERE brief_date = ?"
      ).get(et.date);

      if (!briefToday) {
        const severity = (etHour >= 9) ? 'CRITICAL' : 'WARNING';
        alert(severity, 'NO_BRIEF_TODAY',
          'Daily brief for ' + et.date + ' not generated (current ET time: ' +
          etHour + ':' + String(etMin).padStart(2, '0') +
          '). Daily review fires at 6am ET — if missing by 6:30 something failed.');
      } else {
        console.log('  ✓ daily brief exists for ' + et.date);
      }
    } else {
      console.log('  · brief check skipped (outside 6:30am–11pm ET window)');
    }
  } catch (e) {
    alert('ERROR', 'BRIEF_CHECK_FAIL', e.message);
  }

  // ── CHECK 6: browser task queue depth ────────────────────────────────
  try {
    const queueDepth = db.prepare(
      "SELECT COUNT(*) AS n FROM browser_tasks WHERE status = 'PENDING'"
    ).get().n;

    if (queueDepth > 100) {
      alert('WARNING', 'QUEUE_BACKED_UP',
        queueDepth + ' tasks pending — daemon may be too slow or stuck');
    } else {
      console.log('  ✓ queue depth: ' + queueDepth);
    }
  } catch (e) {
    // Non-fatal
  }

  // ── CHECK 7: unprocessed result backlog (consumer falling behind) ───
  // The consumer runs every 5 min with LIMIT 100. If backlog exceeds 100
  // consistently, the consumer isn't keeping up and signals are delayed.
  try {
    const unprocessed = db.prepare(
      "SELECT COUNT(*) AS n FROM browser_task_results WHERE consumer_processed = 0"
    ).get().n;

    if (unprocessed > 200) {
      alert('WARNING', 'CONSUMER_BACKLOG',
        unprocessed + ' unprocessed results waiting. Consumer is falling behind — ' +
        'increase LIMIT in process_browser_results_vrt2.js or check for errors.');
    } else if (unprocessed > 0) {
      console.log('  · ' + unprocessed + ' unprocessed result(s) pending (under threshold)');
    } else {
      console.log('  ✓ no unprocessed results');
    }
  } catch (e) {
    // Non-fatal
  }

  // ── EMIT ALERTS ──────────────────────────────────────────────────────
  console.log('');
  if (ALERTS.length === 0) {
    console.log('✓ All checks passed');
    db.close();
    return 0;
  }

  console.log('═══════════════════════════════════════════════════════════');
  console.log('ALERTS: ' + ALERTS.length);
  console.log('═══════════════════════════════════════════════════════════');

  const logLines = [];
  ALERTS.forEach(function(a) {
    const line = '[' + new Date(NOW).toISOString() + '] [' + a.severity + '] [' + a.code + '] ' + a.msg;
    console.log(line);
    logLines.push(line);
  });

  try {
    fs.appendFileSync(ALERTS_LOG, logLines.join('\n') + '\n');
  } catch (e) {
    console.error('Failed to write ALERTS.log:', e.message);
  }

  // macOS notification — collapse to one notification with the highest severity
  const critical = ALERTS.filter(function(a) { return a.severity === 'CRITICAL'; });
  const errors   = ALERTS.filter(function(a) { return a.severity === 'ERROR'; });
  const warnings = ALERTS.filter(function(a) { return a.severity === 'WARNING'; });

  if (critical.length > 0) {
    notify('CLAW VRT2 — CRITICAL', critical[0].msg);
  } else if (errors.length > 0) {
    notify('CLAW VRT2 — ERROR', errors[0].msg);
  } else if (warnings.length > 0) {
    notify('CLAW VRT2 — Warning', warnings[0].msg);
  }

  db.close();
  return (critical.length + errors.length > 0) ? 1 : 0;
})().then(function(code) {
  process.exit(code || 0);
}).catch(function(e) {
  console.error('FATAL:', e.message);
  console.error(e.stack);
  process.exit(2);
});
